name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Ensure this matches your project version

      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: dotnet test --logger trx --results-directory TestResults
